version: 2.1
jobs:
  lint:
    docker:
      - image: hseeberger/scala-sbt:8u222_1.3.2_2.12.10
    steps:
      - checkout
      - restore_cache:
          key: sbt-cache
      - run: sbt ++2.12.10! check
      - save_cache:
          key: sbt-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
  test212_jdk8:
    docker:
      - image: hseeberger/scala-sbt:8u222_1.3.2_2.12.10
    steps:
      - checkout
      - restore_cache:
          key: sbt-cache
      - run: sbt ++2.12.10! test packageDoc
      - save_cache:
          key: sbt-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
  test212_jdk11:
    docker:
      - image: hseeberger/scala-sbt:11.0.4_1.3.2_2.12.10
    steps:
      - checkout
      - restore_cache:
          key: sbt-cache
      - run: sbt ++2.12.10! test
      - save_cache:
          key: sbt-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
  test211_jdk8:
    docker:
      - image: hseeberger/scala-sbt:8u222_1.3.2_2.12.10
    steps:
      - checkout
      - restore_cache:
          key: sbt-cache
      - run: sbt ++2.11.12! test packageDoc
      - save_cache:
          key: sbt-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
  test211_jdk11:
    docker:
      - image: hseeberger/scala-sbt:8u222_1.3.2_2.12.10
    steps:
      - checkout
      - restore_cache:
          key: sbt-cache
      - run: sbt ++2.11.12! test
      - save_cache:
          key: sbt-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
  release:
    docker:
      - image: hseeberger/scala-sbt:8u222_1.3.2_2.12.10
    steps:
      - checkout
      - run: git fetch --tags
      - restore_cache:
          key: sbt-cache
      - run: echo -n "${PGP_PUBLIC}" | base64 -d > /tmp/public.asc
      - run: echo -n "${PGP_SECRET}" | base64 -d > /tmp/secret.asc
      - run: echo "credentials += Credentials(\"Sonatype Nexus Repository Manager\", \"oss.sonatype.org\", \"$SONATYPE_USER\", \"$SONATYPE_PASSWORD\")" > ~/.sbt/1.0/sonatype.sbt
      - run: sbt ++2.12.10! clean sonatypeBundleClean +publishSigned sonatypeBundleRelease

workflows:
  version: 2
  build:
    jobs:
      - lint:
          filters:
            tags:
              only: /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/
      - test212_jdk8:
          requires:
            - lint
          filters:
            tags:
              only: /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/
      - test212_jdk11:
          requires:
            - lint
          filters:
            tags:
              only: /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/
      - test211_jdk8:
          requires:
            - lint
          filters:
            tags:
              only: /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/
      - test211_jdk11:
          requires:
            - lint
          filters:
            tags:
              only: /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/
      - release:
          context: Sonatype
          requires:
            - test212_jdk8
            - test212_jdk11
            - test211_jdk8
            - test211_jdk11
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/
