version: 2.1
jobs:
  lint:
    docker:
      - image: hseeberger/scala-sbt:8u252_1.3.10_2.13.2
    steps:
      - checkout
      - restore_cache:
          key: sbt-cache
      - run: sbt ++2.13.2! check
      - save_cache:
          key: sbt-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
  test213_jdk8:
    docker:
      - image: hseeberger/scala-sbt:8u252_1.3.10_2.13.2
    steps:
      - checkout
      - restore_cache:
          key: sbt-cache
      - run: sbt ++2.13.2! test packageDoc
      - save_cache:
          key: sbt-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
  test213_jdk11:
    docker:
      - image: hseeberger/scala-sbt:11.0.7_1.3.10_2.13.2
    steps:
      - checkout
      - restore_cache:
          key: sbt-cache
      - run: sbt ++2.13.2! test
      - save_cache:
          key: sbt-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
  test212_jdk8:
    docker:
      - image: hseeberger/scala-sbt:8u252_1.3.10_2.12.11
    steps:
      - checkout
      - restore_cache:
          key: sbt-cache
      - run: sbt ++2.12.11! test packageDoc
      - save_cache:
          key: sbt-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
  test212_jdk11:
    docker:
      - image: hseeberger/scala-sbt:11.0.7_1.3.10_2.12.11
    steps:
      - checkout
      - restore_cache:
          key: sbt-cache
      - run: sbt ++2.12.11! test
      - save_cache:
          key: sbt-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
  test_211_jdk8_jvm:
    steps:
      - checkout
      - restore_cache:
          key: sbt-cache-v2
      - run:
          name: Install JDK
          command: |
            while $(ps aux | grep -i ' apt ' | grep -v grep > /dev/null); do sleep 1; done # Wait for apt to be ready

            sudo rm /etc/apt/sources.list.d/*
            sudo tee /etc/apt/sources.list > /dev/null \<< 'EOF'
            deb http://mirror.math.princeton.edu/pub/ubuntu/ xenial main universe
            deb http://mirror.math.princeton.edu/pub/ubuntu/ xenial-updates main universe
            deb http://mirror.math.princeton.edu/pub/ubuntu/ xenial-backports main universe
            deb http://mirror.math.princeton.edu/pub/ubuntu/ xenial-security main restricted universe
            EOF

            if [ $JDK_VERSION == 11 ]; then
              wget -qO - https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public | sudo apt-key add -
              sudo add-apt-repository https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/ -y
            fi
            sudo apt update
            if [ $JDK_VERSION == 11 ]; then
              sudo apt install -y adoptopenjdk-11-hotspot
            elif [ $JDK_VERSION == 8 ]; then
              sudo apt install -y openjdk-8-jdk
            fi
            java -version

            echo "deb https://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list
            curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | sudo apt-key add
            sudo apt-get update
            sudo apt-get install sbt
      - run:
          name: Run tests
          command: sbt ++${SCALA_VERSION}! test:compile # 2.11 tests via embedded kafka no longer supported after kafka version 2.4.1
      - run:
          name: Clean unwanted files from cache
          command: |
            rm -fv $HOME/.ivy2/.sbt.ivy.lock
            find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
            find $HOME/.sbt        -name "*.lock"               -print -delete
      - save_cache:
          key: sbt-cache-v2
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
            - "~/.cache"
    machine:
      image: ubuntu-1604:201903-01
    environment:
      - SCALA_VERSION: 2.11.12
      - JDK_VERSION: 8

  release:
    docker:
      - image: hseeberger/scala-sbt:8u252_1.3.10_2.13.2
    steps:
      - checkout
      - run: git fetch --tags
      - restore_cache:
          key: sbt-cache
      - run: echo -n "${PGP_PUBLIC}" | base64 -d > /tmp/public.asc
      - run: echo -n "${PGP_SECRET}" | base64 -d > /tmp/secret.asc
      - run: echo "credentials += Credentials(\"Sonatype Nexus Repository Manager\", \"oss.sonatype.org\", \"$SONATYPE_USER\", \"$SONATYPE_PASSWORD\")" > ~/.sbt/1.0/sonatype.sbt
      - run: sbt ++2.13.1! clean sonatypeBundleClean +publishSigned sonatypeBundleRelease

workflows:
  version: 2
  build:
    jobs:
      - lint:
          filters:
            tags:
              only: /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/
      - test213_jdk8:
          requires:
            - lint
          filters:
            tags:
              only: /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/
      - test213_jdk11:
          requires:
            - lint
          filters:
            tags:
              only: /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/
      - test212_jdk8:
          requires:
            - lint
          filters:
            tags:
              only: /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/
      - test212_jdk11:
          requires:
            - lint
          filters:
            tags:
              only: /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/
      - test_211_jdk8_jvm:
          requires:
            - lint
          filters:
            tags:
              only: /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/
      - release:
          context: Sonatype
          requires:
            - test213_jdk8
            - test213_jdk11
            - test212_jdk8
            - test212_jdk11
            - test_211_jdk8_jvm
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/
